server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml8.yaml

clients:
  - url: ${loki_url}/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
      - regex:
          source: attrs
          expression: '(?P<tag>[^\s]+)\s+(?P<time>\S+)\s+(?P<container_name>\S+)' 
      - labels:
          tag:
          container_name:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: output